# Generated by Django 5.1.5 on 2026-09-30 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_varianteproducto_remove_producto_stock_and_more'),
        ('ventas', '0008_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_venta', to='productos.varianteproducto'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta'),
        ),
    ]
