# Generated by Django 5.1.5 on 2026-09-30 01:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_negocio_establecimiento_negocio_punto_expedicion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('talle', models.CharField(blank=True, max_length=30)),
                ('medida', models.CharField(blank=True, max_length=50)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='productos.negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.negocio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='productos.negocio'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('negocio', 'codigo'), name='codigo_producto_por_negocio'),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.varianteproducto'),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'codigo'), name='codigo_variante_por_producto'),
        ),
    ]
