# Generated by Django 5.1.5 on 2026-10-02 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_varianteproducto_remove_producto_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizar_ventas', models.BooleanField(default=True)),
                ('ver_productos', models.BooleanField(default=True)),
                ('agregar_producto', models.BooleanField(default=False)),
                ('editar_producto', models.BooleanField(default=False)),
                ('eliminar_producto', models.BooleanField(default=False)),
                ('clientes', models.BooleanField(default=True)),
                ('proveedores', models.BooleanField(default=False)),
                ('compras', models.BooleanField(default=False)),
                ('reporte_ventas', models.BooleanField(default=False)),
                ('graficos', models.BooleanField(default=False)),
                ('caja', models.BooleanField(default=True)),
                ('usuarios', models.BooleanField(default=False)),
                ('administracion_tecnica', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
