# Generated by Django 5.1.5 on 2026-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisousuario',
            name='aplicar_descuentos',
            field=models.BooleanField(default=False),
        ),
    ]
